#!/usr/bin/env ruby

require_relative './spec'
require_relative 'lib/extractor'
require_relative 'lib/data_transformer'
require_relative 'lib/generator'
require_relative 'lib/statement'

source_filename = ARGV[0]
output_filename = ARGV[1]

raw_statements = Extractor.extract_statements(source_filename)

statements = raw_statements.map do |statement|
  Statement.new(
    statement[:description],
    DataTransformer.amount(statement[:amount]),
    DataTransformer.date(statement[:date]),
    statement.dig(:installments, :current),
    statement.dig(:installments, :total),
  )
end

File.write(output_filename, Generator.new(statements).generate)
