#!/usr/bin/env ruby

require_relative './spec'
require_relative 'lib/extractor'
require_relative 'lib/data_transformer'
require_relative 'lib/ofx_generator'
require_relative 'lib/statement'

filename = ARGV[0]

raw_statements = Extractor.extract_statements(filename)

statements = raw_statements.map do |statement|
  Statement.new(
    statement[:description],
    DataTransformer.amount(statement[:amount]),
    DataTransformer.date(statement[:date])
  )
end

puts OfxGenerator.new(statements).generate
